# Generated by Django 3.2.2 on 2021-05-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
