# Generated by Django 3.2.2 on 2021-05-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                ("year", models.IntegerField(primary_key=True, serialize=False)),
                ("wiki_url", models.URLField(db_column="url", unique=True)),
            ],
        ),
    ]
