# Generated by Django 3.2.2 on 2021-05-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        ("constructors", "0001_initial"),
        ("races", "0002_alter_race_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qualifying",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="races.race"
                    ),
                ),
                (
                    "constructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="constructors.constructor",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="drivers.driver"
                    ),
                ),
                ("number", models.IntegerField()),
                ("position", models.IntegerField(null=True)),
                ("q1", models.CharField(max_length=255, null=True)),
                ("q2", models.CharField(max_length=255, null=True)),
                ("q3", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
