# Generated by Django 3.2.2 on 2021-05-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.IntegerField()),
                ('wiki_url', models.URLField(db_column='url', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('wiki_url', models.URLField(db_column='url')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('number', models.IntegerField(null=True)),
                ('code', models.CharField(max_length=3, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('wiki_url', models.URLField(db_column='url', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.circuit')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('wiki_url', models.URLField(db_column='url', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('wiki_url', models.URLField(db_column='url', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.race')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.driver')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.constructor')),
                ('number', models.IntegerField(null=True)),
                ('grid', models.IntegerField()),
                ('position', models.IntegerField(null=True)),
                ('position_text', models.CharField(max_length=255)),
                ('position_order', models.IntegerField()),
                ('points', models.FloatField()),
                ('laps', models.IntegerField()),
                ('time', models.CharField(max_length=255, null=True)),
                ('milliseconds', models.FloatField(null=True)),
                ('fastest_lap', models.IntegerField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('fastest_lap_time', models.CharField(max_length=255, null=True)),
                ('fastest_lap_speed', models.CharField(max_length=255, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.status')),
            ],
        ),
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.race')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.driver')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.constructor')),
                ('number', models.IntegerField()),
                ('position', models.IntegerField(null=True)),
                ('q1', models.CharField(max_length=255, null=True)),
                ('q2', models.CharField(max_length=255, null=True)),
                ('q3', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
