# Generated by Django 3.2.2 on 2021-05-15 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backmarker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorResult',
            fields=[
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.race')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.constructor')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
