# Generated by Django 3.2.2 on 2021-05-15 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backmarker', '0002_constructorresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.race')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.constructor')),
                ('points', models.FloatField()),
                ('position', models.IntegerField(null=True)),
                ('position_text', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('wins', models.IntegerField()),
            ],
        ),
    ]
