# Generated by Django 3.2.2 on 2021-05-15 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backmarker', '0003_constructorstanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='LapTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.race')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.driver')),
                ('lap', models.IntegerField()),
                ('position', models.IntegerField(null=True)),
                ('time', models.CharField(max_length=255, null=True)),
                ('milliseconds', models.IntegerField(null=True)),
            ],
        ),
    ]
