# Generated by Django 3.2.2 on 2021-05-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backmarker', '0004_laptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.race')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backmarker.driver')),
                ('points', models.FloatField()),
                ('position', models.IntegerField(null=True)),
                ('position_text', models.CharField(max_length=255, null=True)),
                ('wins', models.IntegerField()),
            ],
        ),
    ]
