# Generated by Django 3.2.2 on 2021-05-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backmarker', '0006_pitstop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructorstanding',
            name='status',
        ),
    ]
