# Generated by Django 3.2.2 on 2021-05-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circuits", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="circuit",
            old_name="url",
            new_name="wiki_url",
        ),
        migrations.AlterField(
            model_name="circuit",
            name="wiki_url",
            field=models.URLField(db_column="url", unique=True),
        ),
    ]
